

define( [], function () {
    'use strict';
    return {
        'DE': {
			MainSettings: "Haupteinstellung",
			Inputbox: "EingabeFeld",
			Select: "Drobdown Liste",
			Button: "Schaltfläche",
			DatePicker: "Kalenderbox",
			Slider: "Schiebregler",
			SliderType: "Schiebregler Art",
			SliderTypeA:"Einfach (1 Wert)",
			SliderTypeB:"Bereich (2 Werte)",
			Variable: "Variable",
			Field: "Feld",
			VariableName: "Variablen Name",
			FieldName: "Feld Name",
			ValueSettings: "Standardwerte Einstellungen",
			SliderSettings: "Schiebregler Einstellungen",
			DatePickerSettings: "Kalenderbox Einstellungen",
			astyle: "Aussehen",
			info: "Info (Hilfe)",
			setValuesWith: "setze Wert(e) mit",
			getFromField: "hole Werte aus Feld",
			setAlternative: "eigene Werte",
			commaStr: "nutze Kommaseper. Text",
			fieldNameForVal: "Feldname für die Werte",
			alwaysAllVal: "immer alle Werte nutzen",
			On: "Ein",
			Off: "Aus",
			AddAlternative:"Wert hinzufügen",
			varValues: "varValues",
			commaSepStr:"Kommasepar. Text",
			useForMinMax:"nutze für min und max",
			setMiMa: "setzte min & max",
			getminff: "hole min aus Feld",
			getmaxff: "hole max aus Feld",
			getmmff: "hole min & max aus Feld",
			step: "Step",
			defaultVal: "Default Value",
			dateformat:"Datumsformat",
			showmultimonth: "zeige 3 Monate",
			showButtonPanel: "zeige Schaltflächen",
			restrictDate: "Datum einschrängen",
			restrictSample: "nutze -10 oder -2M 10D oder +1M 5D oder +10",
			rdMin:"Min Datum",
			rdMax: "Max Datum",
			NameLabel: "Bezeichnung Label",
			showLabels: "zeige Bezeichnungen",
			styleType: "Farben aus Vorlage / Hex",
			ownExpression: "Eigene Formel",
			showLabelsBold: "Bezeichnungen in fett",
			maxWidthLabel: "breite für das Label",
			ownWidth: "eigene Breitenangaben",
			objectWidth: "Objekt Breite"
			
		},
		'US':{
			MainSettings: "Haupteinstellung",
			Inputbox: "Inputbox",
			Select: "Select",
			Button: "Button",
			DatePicker: "Datepicker",
			Slider: "Slider",
			SliderType: "Slider Type",
			SliderTypeA:"Single (1 Value)",
			SliderTypeB:"Range (2 Values)",
			Variable: "Variable",
			Field: "Field",
			VariableName: "VariableName",
			FieldName: "Field Name",
			ValueSettings: "Default Value Settings",
			SliderSettings: "Slider Settings",
			DatePickerSettings: "DatePicker Settings",
			astyle: "Style",
			info: "Info (Help)",
			setValuesWith: "set Value(s) with",
			getFromField: "get Values from Field",
			setAlternative: "set Alternatives",
			commaStr: "use Comma Seperated String",
			fieldNameForVal: "Field Name for Values",
			alwaysAllVal: "Always use ALL Values",
			On: "Ein",
			Off: "Aus",
			AddAlternative:"Add Alternative",
			varValues: "varValues",
			commaSepStr:"comma seperated String",
			useForMinMax:"use for min and max",
			setMiMa: "set min & max",
			getminff: "get min from Field",
			getmaxff: "get max from Field",
			getmmff: "get min & max from Field",
			step: "Step",
			defaultVal: "Default Value",
			dateformat:"Dateformat",
			showmultimonth: "show 3 Months",
			showButtonPanel: "show Button Panel",
			restrictDate: "restrict Date",
			restrictSample: "use -10 or -2M 10D or +1M 5D or +10",
			rdMin:"Min Date",
			rdMax: "Max Date",
			NameLabel: "Bezeichnung für das Label",
			showLabels: "zeige Bezeichnungen",
			styleType: "Own Expression",
			showLabelsBold: "Bezeichnungen in fett"
		}
    }
	
} );